[config]
response_language = "ko-KR"
model = "gemini/gemini-2.0-flash"
fallback_models = ["gemini/gemini-1.5-flash"]

[github_action_config]
auto_describe = false
auto_imporeve = true
auto_review = true

[pr_code_suggestions]
commitable_code_suggestions = true
extra_instructions = """\
1. Answer in Korean.
2. Answer with Java code only.
3. Answer only about coding conventions.
    3.1. For a review of the coding convention, see the files below.
        - /code-guidelines.md
"""
